name: ArrowFight
version: '${project.version}'
main: org.mmga.mycraft.arrowfight.ArrowFightPlugin
api-version: 1.16
authors: [ MakeMinecraftGreatAgainTeam ]
description: an arrow fight plugin for mycraft server
depend:
  - Multiverse-Core
  - PlaceholderAPI
website: http://wzpmc.cn:4000/wzp/ArrowFight
commands:
  af:
    permission: arrowfight.command.af
    permission-message: 你没有权限执行此指令
    description: ArrowFight的主指令，使用/af help获取帮助
permissions:
  arrowfight.command.af:
    description: Command af
    default: true